### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Endowmissy** [hngi/is-this-a-real-job#105]
Is like the login page has been tampered with,why is the login button and the register link scattered,shudnt it look like that of the register page??,

**Comment by dokoede** [comment]
I saw it as well. A button was added to enable users login with twitter account.

I have fixed it 

before 
![Screenshot_2019-10-30 Is-This-A-Real-Job Check if job oppurtunities are real (4)](https://user-images.githubusercontent.com/40797562/67892260-a379bd80-fb54-11e9-8670-c50b71a6ba08.png)

After
![Screenshot_2019-10-30 Is-This-A-Real-Job Check if job oppurtunities are real (3)](https://user-images.githubusercontent.com/40797562/67892278-ad9bbc00-fb54-11e9-804b-f75d6729a38b.png)


pr link : https://github.com/hngi/is-this-a-real-job/pull/104
