### ISSUE TITLE
Edit profile button

### ISSUE THREAD

**Issue by gold-olar** [hngi/is-this-a-real-job#152]
I am not signed in as xyluz but i can see an edit profile button when i open xyluz's profile
![Screenshot from 2019-11-01 09-19-25](https://user-images.githubusercontent.com/43508719/68011979-053b4400-fc89-11e9-9543-a41d701a254e.png)

**Comment by LeanKhan** [comment]
Yeah, thanks.

**Comment by gold-olar** [comment]
Has been fixed now
