### ISSUE TITLE
Missing colon causes buid to fail

### ISSUE THREAD

**Issue by cirqlar** [hngi/is-this-a-real-job#22]
https://github.com/hngi/is-this-a-real-job/blob/eff3394a925bb85b2069b5369704f5aff737e151/src/routes/routes.js#L10-L11

There's a missing semicolon in the routes.js file

**Comment by cirqlar** [comment]
There's also multiple clashes between the names of imports.
https://github.com/hngi/is-this-a-real-job/blob/eff3394a925bb85b2069b5369704f5aff737e151/src/routes/routes.js#L10-L20

**Comment by LeanKhan** [comment]
Yeah this was resolved in one of the PR's but it is yet to be merged.

**Comment by cirqlar** [comment]
I'll close it once the PR's merged.
